name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - hml

jobs:
  release:
    uses: glenonmateus/actions/.github/workflows/release.yml@main
    with:
      repository_owner: ${{ github.repository_owner }}
    secrets:
      semantic_release_token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
