name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - hml

jobs:
  release:
    name: Semantic Release
    uses: glenonmateus/actions/.github/workflows/release.yml@main
    with:
      repository_owner: ${{ github.repository_owner }}
    secrets:
      semantic_release_token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

  sync-branch:
    needs: [release]
    name: Sync Branches
    uses: glenonmateus/actions/.github/workflows/sync-branches.yml@main
    if: github.ref == 'refs/heads/main'
    with:
      from_branch: main
      to_branch: hml
