name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - hml

jobs:
  release:
    uses: glenonmateus/actions/.github/workflows/release.yml
    with:
      repository_owner: ${{ github.repository_owner }}
