name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - hml

jobs:
  setting:
    runs-on: ubuntu-latest
    steps:
      - name: Setting releaserc
        if: contains('refs/heads/hml', github.ref)
        run: |
          jq 'del(.plugins[] | select(.[0] |contains("changelog")))' .releaserc.json > .releaserc.json
          echo .releaserc.json
  release:
    name: Semantic Release
    uses: glenonmateus/actions/.github/workflows/release.yml@main
    with:
      repository_owner: ${{ github.repository_owner }}
    secrets:
      semantic_release_token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
